name: Build and Commit Recent Media

on:
  push:
    branches-ignore:
      - 'main'

jobs:
  build-and-commit:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout external repo
        uses: actions/checkout@v3
        with:
          repository: agoodkind/instagram-recents-go  # Replace with the actual owner/repo
          ref: ${{ github.ref_name }}
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'  # Adjust to your Go version
      
      - name: Build
        run: go build -v ./...
      
      - name: Run
        run: ./instagram-recents-go 
        env:
          INSTAGRAM_DEVELOPMENT_ACCESS_TOKEN: ${{ secrets.INSTAGRAM_DEVELOPMENT_ACCESS_TOKEN }}
           
      
      - name: Commit and push
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add recent_media.json
          git commit -m "Update recent media data" || echo "No changes to commit"
          git push 